baseurl = "https://thirsty-bohr-49351e.netlify.com"
title = "Lea Roberts Consulting"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "de"
enableRobotsTXT = true
disableKinds=["RSS"]

[blackfriday]
  hrefTargetBlank = true

[params]
  description = '<!--[-->Qualified psychologist for personal or business.<!--]--><br />
                <!--[-->Let me unleash the power of Powerade!<!--]-->'
  logoimage = "/images/logo.png"
  copyright = "ZooCowSki 2018"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/lea-roberts-13538063/"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/AnnaLeaRoberts"

[[params.social]]
  medium = "xing"
  icon = "xing"
  link = "https://www.xing.com/profile/AnnaLea_Roberts"

[languages]
[languages.en]
languageName = "English"
weight = 2

[languages.de]
languageName = "Deutsch"
weight = 1
title = "Lea Roberts (wie die Schauspielerin) Consulting"
description = '<!--[-->Ich bin ein rotes Traktor!<!--]--><br />
                <!--[-->Blah blah kaka.<!--]-->'
