baseurl = "https://thirsty-bohr-49351e.netlify.com"
title = "Lea Roberts"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = '<!--[-->Qualified psychologist for personal or business.<!--]--><br />
                <!--[-->Let me unleash the power of Powerade!<!--]-->'
  logo = "images/logo.png"
  copyright = "DJ Roberts Design 2017"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "#"

[languages]
[languages.en]
languageName = "English"
weight = 1

[languages.de]
languageName = "Deutsch"
weight = 2
title = "Dimension"
description = '<!--[-->A fully responsive site template designed by <a href="https://html5up.net">HTML5 UP</a> and released<!--]--><br />
                <!--[-->for free under the <a href="https://html5up.net/license">Creative Commons</a> license.<!--]-->'
