# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Dimension"
license = "Creative Commons Attribution 3.0 Unported"
licenselink = "https://github.com/szukalski/dimension/blob/master/LICENSE.md"
description = "Dimension is a single page and responsive site template using modals as pages."
homepage = "https://github.com/szukalski/dimension"
tags = ["responsive", "personal", "portfolio", "multilingual"]
features = ["responsive", "multilingual"]
min_version = 0.18

[author]
  name = "DJ Roberts"
  homepage = "https://www.zoocowski.com/"

# If porting an existing theme
[original]
  name = "Seth MacLeod"
  homepage = "https://www.sethmacload.com/"
  repo = ""
